<?php

namespace Database\Seeders;

use App\Models\Zone;
use Illuminate\Database\Seeder;

class ZoneSeeder extends Seeder
{
    public function run(): void
    {
        $zones = [
            [
                'name' => '6 Miles',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 25 - A',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Airwing - Acacia',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Airwing - After Barons',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Airwing - Four Ways',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 1 (Falls)',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 10',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 12',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 13 (City Center)',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 14',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 15',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 17',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 22',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 23',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 24',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 25 - Magwero',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 27',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 3',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 32',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 34',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 36',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 38',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 39',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 43',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 44',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 45',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 46',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 47 - Sector 1',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 49 - Old Gulliver',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 50',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 51',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 58',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 9',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Airwing - Baron',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Airwing - Before Four Ways',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 49 - Bhagdad',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Biwi',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Airwing - Buli',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Airwing - Buli Road',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 25 - B',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Bunda - College',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Bunda - Chiseka',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Bwemba',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Bypass',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 25 - C',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'CCDC',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Likuni - Chigwiri',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Chilinde',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Chinsapo 2',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Chitedze',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Chitipi',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Chitipi Road',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Chitukula',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 25 - Choto',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 25 - Dzenza',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Likuni - Forest',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Bunda - Guzani',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Kaliyeka',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Kanengo',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Kaphiri',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Kawale 1',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Kawale 2',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Likuni - Chinsapo 1',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Likuni - Magulosale',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Likuni - Malewezi',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Airwing - Mbavi',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Mbwatalika',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Mchesi',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Bunda - Mitundu',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Likuni - Mpapha',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Mpingu',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 25 - Msungwi',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Mtandile',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Mtandile - Chilimampunga',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Mtaya',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Airwing - Muzu',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'NRC',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Nanjiri',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Nathenje',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'New Airwing',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 49 - New Gulliver',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 49 - New Shire',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Njewa',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 49 - Old Shire',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Old Town',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Bunda - Pondamali',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Airwing - Sankhani',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Sector 1',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 25 - Sector 2',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 49 - Sector 3',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 49 - Sector 4',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Area 49 - Sector 5',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
            [
                'name' => 'Likuni Works',
                'cost' => 0,
                'level' => 1,
                'coordinates' => [],
            ],
        ];

        foreach ($zones as $zone) {
            Zone::updateOrCreate(
                ['name' => $zone],
                [
                    'cost' => 0,
                    'level' => 1,
                    'coordinates' => [],
                ]
            );
        }
    }
}
