<template>
  <app-layout>
    <template #header>
      Receipts
    </template>

    <template #breadcrumbs>
      <li aria-current="page">
        <div class="flex items-center">
          <svg class="w-6 h-6 text-gray-400" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd"
              d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
              clip-rule="evenodd"></path>
          </svg>
          <span class="heading-font uppercase text-sm font-medium text-gray-500 dark:text-gray-400">
            Receipts
          </span>
        </div>
      </li>
    </template>

    <template #actions>

    </template>

    <div class="py-6">
      <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">

        <div class="page-section">
          <div class="page-section-header">
            <div class="page-section-title">
              All
            </div>
          </div>
          <div class="page-section-content">

            <div v-if="receipts.data.length === 0" class="text-center text-gray-400 md:col-span-2 text-sm">
              No Receipts Found
            </div>
            <div v-else>

              <div class="card">
                <div class="p-2 mb-2 relative ">
                  <div class="p-2 pb-4 heading-font text-left relative">
                    <button v-show="search > 0" @click="search = ''"
                      class="absolute top-5 right-4 h-5 w-5 close-field rounded-full bg-white p-1 hover:bg-gray-300 flex justify-center items-center transition ease-out duration-500">
                      <i class="mdi mdi-close"></i>
                    </button>
                    <jet-input id="code" type="text" class="block w-full" placeholder="Search for receipt..."
                      v-model="search" autocomplete="seposale-filter-search" />

                  </div>
                  <table class="w-full  text-left text-gray-500 dark:text-gray-400">
                    <thead class="mb-8 text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">

                      <tr>
                        <th scope="col" class="p-2 pb-0 heading-font text-left">Date</th>
                        <th scope="col" class="p-2 pb-0 heading-font text-left">Sale Code</th>
                        <th scope="col" class="p-2 pb-0 heading-font text-left">Receipt Code</th>
                        <th scope="col" class="p-2 pb-0 heading-font text-left">Client</th>
                        <th scope="col" class="p-2 pb-0 heading-font text-left">Payment Method</th>
                        <th scope="col" class="p-2 pb-0 heading-font text-right">Amount</th>
                        <th scope="col" class="p-2 pb-0 heading-font text-left">Generated By</th>
                        <th scope="col" class="p-2 pb-0 heading-font text-left">Mapped</th>

                      </tr>

                    </thead>
                    <tbody class="pt-8">

                      <tr class="border-b cursor-pointer hover:bg-gray-100 transition ease-in-out duration-200"
                        v-for="(receipt, index) in filteredReceipts" :key="index">

                        <td class="p-2 text-left ">{{ getDate(receipt.date * 1000) }}</td>
                        <td>
                          <span v-if="receipt.sale != null" @click="navigateToSale(receipt.sale.id)" class="p-2 text-left">{{ receipt.sale.code }}
                          </span>
                          
                        </td>
                        <td class="p-2 text-left">{{ receipt.code }}</td>
                        <td @click="navigateToClient(receipt.client.id)" class="p-2 text-left ">{{ receipt.client.name
                        }}
                        </td>
                        <td class="p-2 text-left ">{{ receipt.paymentMethod }}</td>
                        <td class="p-2 text-left ">{{ receipt.amount }}</td>
                        <td class="p-2 text-left ">{{ receipt.generatedBy.fullName }}</td>
                        <td>
                          <input id="default-radio-1" :checked="receipt.transaction" type="checkbox" disabled
                            class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        </td>

                      </tr>
                    </tbody>
                  </table>
                </div>

              </div>

              <!-- <div class="grid grid-cols-1 md:grid-cols-2">
                <inertia-link :href="route('receipts.show', { id: receipt.id })"
                  v-for="(receipt, index) in receipts.data" :key="index">
                  <div class="app-card">
                    <div class="header justify-between items-center border-b">
                      <div>
                        <div>
                          <span class="date rounded py-1 px-2 bg-gray-200 text-gray-600 text-xs font-bold uppercase">{{
                            getDate(receipt.date * 1000)
                            }}</span>
                        </div>
                        <div class="type">#{{ receipt.code }}</div>


                      </div>
                      <div class="flex items-center ">
                        <div class="currency ">MK</div>
                        <div class="total">{{ numberWithCommas(receipt.amount) }}</div>
                      </div>
                    </div>
                    <div>
                      <div class="name font-normal ml-3 flex justify-between">
                        <div>{{ receipt.client.name }}</div>
                        <div>{{ receipt.paymentMethod }}</div>
                      </div>
                    </div>
                  </div>
                </inertia-link>
              </div>



              <div class="flex flex-col items-center">
                
                <span class="text-sm text-gray-700 dark:text-gray-400">
                  Showing <span class="font-semibold text-gray-900 dark:text-white">{{
                    receipts.meta.from
                  }}</span> to <span class="font-semibold text-gray-900 dark:text-white">{{ receipts.meta.to }}</span>
                  of
                  <span class="font-semibold text-gray-900 dark:text-white">{{
                    receipts.meta.total
                    }}</span> Invoices
                </span>
                <div class="inline-flex mt-2 xs:mt-0">
                  <a :href="receipts.links.prev"
                    class="inline-flex items-center px-4 py-2 mr-3 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                    <svg aria-hidden="true" class="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd"
                        d="M7.707 14.707a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l2.293 2.293a1 1 0 010 1.414z"
                        clip-rule="evenodd"></path>
                    </svg>
                    Previous
                  </a>
                  <a :href="receipts.links.next"
                    class="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-500 bg-white border border-gray-300 rounded-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">
                    Next
                    <svg aria-hidden="true" class="w-5 h-5 ml-2" fill="currentColor" viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd"
                        d="M12.293 5.293a1 1 0 011.414 0l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-2.293-2.293a1 1 0 010-1.414z"
                        clip-rule="evenodd"></path>
                    </svg>
                  </a>
                </div>
              </div> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </app-layout>
</template>

<script>
import AppLayout from '@/Layouts/AppLayout'
import DoughnutChart from "@/Components/Charts/DoughnutChart";
import PieChart from "@/Components/Charts/PieChart";
import Request from "@/Components/Request";
import PrimaryButton from "@/Jetstream/Button";
import SaleStatus from "@/Components/SaleStatus.vue";
import JetInput from "@/Jetstream/Input";


export default {
  props: [
    'receipts',
  ],
  components: {
    SaleStatus,
    AppLayout,
    PrimaryButton,
    JetInput,
  },
  data() {
    return {
      search: ""
    }
  },
  computed: {
    filteredReceipts() {
      let filtered = this.receipts.data

      /* Filter Sales By Client*/
      if (this.search.length !== 0) {
        filtered = (filtered).filter((receipt) => {
          if (receipt.paymentMethod != null) {
            return receipt.code.toLowerCase().includes(this.search.toLowerCase()) ||
              receipt.client.name.toLowerCase().includes(this.search.toLowerCase()) ||
              // receipt.sale.code.toLowerCase().includes(this.search.toLowerCase()) ||
              receipt.paymentMethod.toLowerCase().includes(this.search.toLowerCase())

          }
          else {
            return receipt.code.toLowerCase().includes(this.search.toLowerCase()) ||
            // receipt.sale.code.toLowerCase().includes(this.search.toLowerCase()) ||
              receipt.client.name.toLowerCase().includes(this.search.toLowerCase())

          }
        })
      }

      return filtered
    },
  },
  methods: {
    navigateToInvoice(id) {
      this.$inertia.get(this.route('receipts.show', { 'id': id }))
    },
    navigateToClient(id) {
      this.$inertia.get(this.route('clients.show', { 'id': id }))
    },
    navigateToSale(id) {
      this.$inertia.get(this.route('sales.show', { 'id': id }))
    },
  }
}
</script>
